linters:
  enable:
    # default
    #- deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    #- structcheck
    - typecheck
    - unused
    #- varcheck
    - depguard
    - dupl
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - exportloopref
    - stylecheck
    - unconvert
    #- unparam
    - gosec
    - revive
    - godot
  disable:
    - lll
    - maligned
linters-settings:
  errcheck:
    ignore: fmt:.*

run:
  modules-download-mode: readonly
  timeout: 2m
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
#        - gocyclo
#        - errcheck
        - dupl
        - gosec